import bcrypt from 'bcrypt';


const saltRounds = 10;
const hashedPassword1 = bcrypt.hashSync("P@ssw0rd1", saltRounds);
const hashedPassword2 = bcrypt.hashSync("Str0ngP@ssw0rd2", saltRounds);
const hashedPassword3 = bcrypt.hashSync("C0mpl3xP@ssw0rd3", saltRounds);
const hashedPassword4 = bcrypt.hashSync("S3cur3P@ssw0rd4", saltRounds);
const hashedPassword5 = bcrypt.hashSync("H@rdT0Gu3ssP@ssw0rd5", saltRounds);
const hashedPassword6 = bcrypt.hashSync("Unbr3ak@bl3P@ssw0rd6", saltRounds);
const hashedPassword7 = bcrypt.hashSync("P@ssw0rd7!", saltRounds);
const hashedPassword8 = bcrypt.hashSync("Str0ngP@ssw0rd8!", saltRounds);
const hashedPassword9 = bcrypt.hashSync("C0mpl3xP@ssw0rd9!", saltRounds);
const hashedPassword10 = bcrypt.hashSync("S3cur3P@ssw0rd10!", saltRounds);
const hashedPassword11 = bcrypt.hashSync("H@rdT0Gu3ssP@ssw0rd11!", saltRounds);
const hashedPassword12 = bcrypt.hashSync("Unbr3ak@bl3P@ssw0rd12!", saltRounds);
const hashedPassword13 = bcrypt.hashSync("P@ssw0rd13#", saltRounds);
const hashedPassword14 = bcrypt.hashSync("Str0ngP@ssw0rd14#", saltRounds);
const hashedPassword15 = bcrypt.hashSync("C0mpl3xP@ssw0rd15#", saltRounds);
const hashedPassword16 = bcrypt.hashSync("S3cur3P@ssw0rd16#", saltRounds);
const hashedPassword17 = bcrypt.hashSync("H@rdT0Gu3ssP@ssw0rd17#", saltRounds);
const hashedPassword18 = bcrypt.hashSync("Unbr3ak@bl3P@ssw0rd18#", saltRounds);
const hashedPassword19 = bcrypt.hashSync("P@ssw0rd19$", saltRounds);
const hashedPassword20 = bcrypt.hashSync("Str0ngP@ssw0rd20$", saltRounds);
const hashedPassword21 = bcrypt.hashSync("C0mpl3xP@ssw0rd21$", saltRounds);
const hashedPassword22 = bcrypt.hashSync("S3cur3P@ssw0rd22$", saltRounds);
const hashedPassword23 = bcrypt.hashSync("H@rdT0Gu3ssP@ssw0rd23$", saltRounds);
const hashedPassword24 = bcrypt.hashSync("Unbr3ak@bl3P@ssw0rd24$", saltRounds);
export const sampleUsers = [
  {
    firstName: "Liam",
    surName: "Smith",
    email: "liam@example.com",
    age: 28,
    password: hashedPassword1,
    gender: "Male",
    verification: true,
    user_profile_pic: "user_default_male.png",
    userProfile: {
      primary_motivation: "To seek understanding and support from others",
      professional_treatment: "Yes, but I'm not currently in treatment.",
      comfortable_discussing_mental_health: "Yes, I'm very open about it.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Agnostic",
      received_a_diagnosis: "No",
      age: 28,
      gender_identity: "Male",
      sexual_orientation: "Gay",
      religious_identity: "No, I am not religious.",

    },
    interestsAndQuestions:{
      depression: false,
      anxiety: true,
      bipolar: false,
      ptsd: true,
      ocd: false,
      schizophrenia: false,
      eatingDisorders: true,
      other: false,
      eating_disorders: true,
      copingTechniques: true,
      personalStories: false,
      medication: true,
      reducingStigma: false,
      healthyLifestyle: false,
      spirituality: false,
      otherInterests: false,
      meditation: true,
      creativeActivities: false,
      talkToFriends: false,
      exercise: false,
      seekingHelp: true,
      otherCoping: true,
      creative_activities: true,
      talking_to_friends_family: true,
      exercising: true,
      professional_help: false,
      copingother: false,
      coping_techniques: false,
      personal_stories: false,
      reducing_stigma: false,
      healthy_lifestyle: false
    },
    pendingFriends: []
  },
  {
    firstName: "Sophia",
    surName: "Johnson",
    email: "sophia@example.com",
    age: 25,
    password: hashedPassword2,
    gender: "Female",
    verification: true,
    user_profile_pic: "user_default_female.png",
    userProfile: {
      primary_motivation: "To provide support and help to others",
      professional_treatment: "Yes, but I'm not currently in treatment.",
      comfortable_discussing_mental_health: "Yes, I'm very open about it.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Atheism",
      received_a_diagnosis: "No",
      age: 25,
      gender_identity: "Female",
      sexual_orientation: "Bisexual",
      religious_identity: "No, I am not religious.",

    },
    interestsAndQuestions:  {
      depression: true,
      anxiety: false,
      bipolar: false,
      ptsd: true,
      ocd: false,
      schizophrenia: true,
      eatingDisorders: false,
      other: true,
      eating_disorders: true,
      copingTechniques: true,
      personalStories: false,
      medication: true,
      reducingStigma: false,
      healthyLifestyle: false,
      spirituality: true,
      otherInterests: true,
      meditation: true,
      creativeActivities: false,
      talkToFriends: true,
      exercise: false,
      seekingHelp: false,
      otherCoping: true,
      creative_activities: true,
      talking_to_friends_family: true,
      exercising: true,
      professional_help: true,
      copingother: true,
      coping_techniques: true,
      personal_stories: true,
      reducing_stigma: false,
      healthy_lifestyle: true
    },
    pendingFriends: []
  },
  {
    firstName: "Muhammad",
    surName: "Ahmed",
    email: "muhammad@example.com",
    age: 32,
    password: hashedPassword3,
    user_profile_pic: "user_default_male.png",
    gender: "Male",
    verification: true,
    userProfile: {
      primary_motivation: "To gain knowledge about mental health and related topics",
      professional_treatment: "No, but I'm considering seeking treatment.",
      comfortable_discussing_mental_health: "Yes, I'm very open about it.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Islam",
      received_a_diagnosis: "No",
      age: 32,
      gender_identity: "Male",
      sexual_orientation: "Straight",
      religious_identity: "Yes, I am religious.",

    },
    interestsAndQuestions:  {
      depression: true,
      anxiety: false,
      bipolar: false,
      ptsd: true,
      ocd: false,
      schizophrenia: false,
      eatingDisorders: false,
      other: false,
      eating_disorders: false,
      copingTechniques: false,
      personalStories: false,
      medication: true,
      reducingStigma: true,
      healthyLifestyle: true,
      spirituality: true,
      otherInterests: false,
      meditation: false,
      creativeActivities: true,
      talkToFriends: true,
      exercise: true,
      seekingHelp: false,
      otherCoping: false,
      creative_activities: true,
      talking_to_friends_family: true,
      exercising: true,
      professional_help: false,
      copingother: true,
      coping_techniques: true,
      personal_stories: false,
      reducing_stigma: false,
      healthy_lifestyle: true
    },
    pendingFriends: []
  },
  {
    firstName: "Olivia",
    surName: "Martinez",
    email: "olivia@example.com",
    age: 29,
    password: hashedPassword4,
    user_profile_pic: "user_default_female.png",
    gender: "Female",
    verification: true,
    userProfile: {
      primary_motivation: "To provide support and help to others",
      professional_treatment: "No, and I am not interested in seeking treatment.",
      comfortable_discussing_mental_health: "No, I prefer to keep it private.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Buddhism",
      received_a_diagnosis: "No",
      age: 29,
      gender_identity: "Female",
      sexual_orientation: "Pansexual",
      religious_identity: "Yes, I am religious.",

    },
    interestsAndQuestions:
    {
      depression: true,
      anxiety: true,
      bipolar: false,
      ptsd: true,
      ocd: false,
      schizophrenia: true,
      eatingDisorders: false,
      other: true,
      eating_disorders: true,
      copingTechniques: true,
      personalStories: false,
      medication: false,
      reducingStigma: false,
      healthyLifestyle: true,
      spirituality: true,
      otherInterests: false,
      meditation: false,
      creativeActivities: false,
      talkToFriends: false,
      exercise: false,
      seekingHelp: false,
      otherCoping: true,
      creative_activities: true,
      talking_to_friends_family: true,
      exercising: true,
      professional_help: true,
      copingother: false,
      coping_techniques: true,
      personal_stories: true,
      reducing_stigma: true,
      healthy_lifestyle: true
    },

    pendingFriends: []
  },
  {
    firstName: "Mia",
    surName: "Brown",
    email: "mia@example.com",
    age: 27,
    password: hashedPassword5,
    user_profile_pic: "user_default_female.png",

    gender: "Female",
    verification: true,
    userProfile: {
      primary_motivation: "To seek understanding and support from others",
      professional_treatment: "Yes, I am currently receiving treatment.",
      comfortable_discussing_mental_health: "Yes, I'm very open about it.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Christianity",
      received_a_diagnosis: "Yes",
      age: 27,
      gender_identity: "Female",
      sexual_orientation: "Lesbian",
      religious_identity: "Yes, I am religious.",
    },
    interestsAndQuestions:  {
      depression: false,
      anxiety: true,
      bipolar: false,
      ptsd: false,
      ocd: true,
      schizophrenia: false,
      eatingDisorders: true,
      other: false,
      eating_disorders: true,
      copingTechniques: false,
      personalStories: false,
      medication: false,
      reducingStigma: true,
      healthyLifestyle: true,
      spirituality: true,
      otherInterests: false,
      meditation: false,
      creativeActivities: true,
      talkToFriends: true,
      exercise: true,
      seekingHelp: false,
      otherCoping: false,
      creative_activities: true,
      talking_to_friends_family: false,
      exercising: true,
      professional_help: true,
      copingother: false,
      coping_techniques: true,
      personal_stories: true,
      reducing_stigma: true,
      healthy_lifestyle: true
    },
    pendingFriends: []
  },
  {
    firstName: "Aryan",
    surName: "Patel",
    email: "aryan@example.com",
    age: 22,
    password: hashedPassword6,
    gender: "Male",
    verification: true,
    user_profile_pic: "user_default_male.png",
    userProfile: {
      primary_motivation: "To seek understanding and support from others",
      professional_treatment: "No, and I am not interested in seeking treatment.",
      comfortable_discussing_mental_health: "Somewhat, depending on the context.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Hinduism",
      received_a_diagnosis: "No",
      age: 22,
      gender_identity: "Male",
      sexual_orientation: "Straight",
      religious_identity: "Yes, I am religious.",
 
    },
    interestsAndQuestions:  {
      depression: true,
      anxiety: false,
      bipolar: false,
      ptsd: false,
      ocd: true,
      schizophrenia: false,
      eatingDisorders: true,
      other: true,
      eating_disorders: true,
      copingTechniques: true,
      personalStories: false,
      medication: true,
      reducingStigma: true,
      healthyLifestyle: true,
      spirituality: true,
      otherInterests: false,
      meditation: true,
      creativeActivities: true,
      talkToFriends: false,
      exercise: false,
      seekingHelp: false,
      otherCoping: true,
      creative_activities: false,
      talking_to_friends_family: true,
      exercising: false,
      professional_help: false,
      copingother: false,
      coping_techniques: false,
      personal_stories: true,
      reducing_stigma: true,
      healthy_lifestyle: true
    },
    pendingFriends: []
  },
  {
    firstName: "Amina",
    surName: "Khan",
    email: "amina@example.com",
    age: 31,
    password: hashedPassword7,
    gender: "Female",
    verification: true,
    user_profile_pic: "user_default_female.png",
    userProfile: {
      primary_motivation: "To gain knowledge about mental health and related topics",
      professional_treatment: "Yes, but I'm not currently in treatment.",
      comfortable_discussing_mental_health: "Yes, I'm very open about it.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Islam",
      received_a_diagnosis: "Yes",
      age: 31,
      gender_identity: "Female",
      sexual_orientation: "Straight",
      religious_identity: "Yes, I am religious.",
      interestsAndQuestions:
      {
        depression: false,
        anxiety: true,
        bipolar: false,
        ptsd: true,
        ocd: false,
        schizophrenia: true,
        eatingDisorders: false,
        other: true,
        eating_disorders: false,
        copingTechniques: false,
        personalStories: true,
        medication: true,
        reducingStigma: true,
        healthyLifestyle: false,
        spirituality: true,
        otherInterests: false,
        meditation: true,
        creativeActivities: false,
        talkToFriends: true,
        exercise: false,
        seekingHelp: true,
        otherCoping: false,
        creative_activities: true,
        talking_to_friends_family: false,
        exercising: false,
        professional_help: false,
        copingother: false,
        coping_techniques: false,
        personal_stories: false,
        reducing_stigma: true,
        healthy_lifestyle: false
      },
    },
    pendingFriends: []
  },
  {
    firstName: "Zara",
    surName: "Ali",
    email: "zara@example.com",
    age: 33,
    password: hashedPassword8,
    gender: "Female",
    verification: true,
    user_profile_pic: "user_default_female.png",
    userProfile: {
      primary_motivation: "To seek understanding and support from others",
      professional_treatment: "No, and I am not interested in seeking treatment.",
      comfortable_discussing_mental_health: "Somewhat, depending on the context.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Islam",
      received_a_diagnosis: "Yes",
      age: 33,
      gender_identity: "Female",
      sexual_orientation: "Straight",
      religious_identity: "Yes, I am religious.",

    },
    interestsAndQuestions:
    {
      depression: true,
      anxiety: true,
      bipolar: false,
      ptsd: true,
      ocd: false,
      schizophrenia: true,
      eatingDisorders: true,
      other: false,
      eating_disorders: false,
      copingTechniques: true,
      personalStories: true,
      medication: false,
      reducingStigma: false,
      healthyLifestyle: false,
      spirituality: false,
      otherInterests: true,
      meditation: true,
      creativeActivities: true,
      talkToFriends: false,
      exercise: false,
      seekingHelp: true,
      otherCoping: true,
      creative_activities: true,
      talking_to_friends_family: false,
      exercising: false,
      professional_help: false,
      copingother: false,
      coping_techniques: false,
      personal_stories: false,
      reducing_stigma: true,
      healthy_lifestyle: false
    },

    pendingFriends: []
  },
  {
    firstName: "David",
    surName: "Wilson",
    email: "david@example.com",
    age: 40,
    password: hashedPassword9, 
    gender: "Male",
    verification: true,
    user_profile_pic: "user_default_male.png",
    userProfile: {
      primary_motivation: "To seek understanding and support from others",
      professional_treatment: "Yes, I am currently receiving treatment.",
      comfortable_discussing_mental_health: "Yes, I'm very open about it.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Christianity",
      received_a_diagnosis: "Yes",
      age: 40,
      gender_identity: "Male",
      sexual_orientation: "Straight",
      religious_identity: "Yes, I am religious.",
    
    },
    interestsAndQuestions:
    {
      depression: true,
      anxiety: true,
      bipolar: true,
      ptsd: true,
      ocd: true,
      schizophrenia: false,
      eatingDisorders: false,
      other: true,
      eating_disorders: true,
      copingTechniques: false,
      personalStories: true,
      medication: true,
      reducingStigma: true,
      healthyLifestyle: false,
      spirituality: true,
      otherInterests: false,
      meditation: false,
      creativeActivities: false,
      talkToFriends: false,
      exercise: true,
      seekingHelp: false,
      otherCoping: true,
      creative_activities: false,
      talking_to_friends_family: false,
      exercising: true,
      professional_help: true,
      copingother: false,
      coping_techniques: false,
      personal_stories: false,
      reducing_stigma: true,
      healthy_lifestyle: false
    },
    pendingFriends: []
  },
  {
    firstName: "Amira",
    surName: "Hassan",
    email: "amira@example.com",
    age: 29,
    password: hashedPassword10,
    gender: "Female",
    verification: true,
    user_profile_pic: "user_default_female.png",
    userProfile: {
      primary_motivation: "To provide support and help to others",
      professional_treatment: "No, and I am not interested in seeking treatment.",
      comfortable_discussing_mental_health: "Somewhat, depending on the context.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Islam",
      received_a_diagnosis: "No",
      age: 29,
      gender_identity: "Female",
      sexual_orientation: "Straight",
      religious_identity: "Yes, I am religious.",

    },
    interestsAndQuestions:
    {
      depression: false,
      anxiety: true,
      bipolar: true,
      ptsd: false,
      ocd: true,
      schizophrenia: true,
      eatingDisorders: true,
      other: false,
      eating_disorders: true,
      copingTechniques: false,
      personalStories: true,
      medication: true,
      reducingStigma: false,
      healthyLifestyle: false,
      spirituality: false,
      otherInterests: true,
      meditation: true,
      creativeActivities: false,
      talkToFriends: false,
      exercise: true,
      seekingHelp: true,
      otherCoping: false,
      creative_activities: false,
      talking_to_friends_family: true,
      exercising: true,
      professional_help: false,
      copingother: true,
      coping_techniques: true,
      personal_stories: false,
      reducing_stigma: false,
      healthy_lifestyle: false
    },
    pendingFriends: []
  },
  {
    firstName: "Leo",
    surName: "Miller",
    email: "leo@example.com",
    age: 35,
    password: hashedPassword11,
    gender: "Male",
    verification: true,
    user_profile_pic: "user_default_male.png",
    userProfile: {
      primary_motivation: "To seek understanding and support from others",
      professional_treatment: "Yes, but I'm not currently in treatment.",
      comfortable_discussing_mental_health: "Yes, I'm very open about it.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Atheism",
      received_a_diagnosis: "No",
      age: 35,
      gender_identity: "Male",
      sexual_orientation: "Gay",
      religious_identity: "No, I am not religious.",

    },
    interestsAndQuestions:

    {
      depression: true,
      anxiety: true,
      bipolar: true,
      ptsd: false,
      ocd: false,
      schizophrenia: true,
      eatingDisorders: false,
      other: true,
      eating_disorders: false,
      copingTechniques: false,
      personalStories: false,
      medication: false,
      reducingStigma: false,
      healthyLifestyle: false,
      spirituality: false,
      otherInterests: false,
      meditation: false,
      creativeActivities: false,
      talkToFriends: true,
      exercise: true,
      seekingHelp: false,
      otherCoping: false,
      creative_activities: false,
      talking_to_friends_family: true,
      exercising: true,
      professional_help: false,
      copingother: false,
      coping_techniques: true,
      personal_stories: true,
      reducing_stigma: false,
      healthy_lifestyle: false
    },
    pendingFriends: []
  },
  {
    firstName: "Sofia",
    surName: "Lopez",
    email: "sofia@example.com",
    age: 23,
    password: hashedPassword12,
    gender: "Female",
    verification: true,
    user_profile_pic: "user_default_female.png",
    userProfile: {
      primary_motivation: "To seek understanding and support from others",
      professional_treatment: "No, but I'm considering seeking treatment.",
      comfortable_discussing_mental_health: "Somewhat, depending on the context.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Christianity",
      received_a_diagnosis: "No",
      age: 23,
      gender_identity: "Female",
      sexual_orientation: "Bisexual",
      religious_identity: "Yes, I am religious.",

    },
    interestsAndQuestions:
    {
      depression: true,
      anxiety: false,
      bipolar: true,
      ptsd: true,
      ocd: true,
      schizophrenia: true,
      eatingDisorders: true,
      other: true,
      eating_disorders: true,
      copingTechniques: false,
      personalStories: true,
      medication: true,
      reducingStigma: false,
      healthyLifestyle: true,
      spirituality: false,
      otherInterests: true,
      meditation: true,
      creativeActivities: true,
      talkToFriends: true,
      exercise: false,
      seekingHelp: false,
      otherCoping: false,
      creative_activities: true,
      talking_to_friends_family: false,
      exercising: false,
      professional_help: false,
      copingother: true,
      coping_techniques: false,
      personal_stories: true,
      reducing_stigma: false,
      healthy_lifestyle: false
    },
    pendingFriends: []
  },
  {
    firstName: "Omar",
    surName: "Hussein",
    email: "omar@example.com",
    age: 28,
    password: hashedPassword13,
    gender: "Male",
    verification: true,
    user_profile_pic: "user_default_male.png",
    userProfile: {
      primary_motivation: "To gain knowledge about mental health and related topics",
      professional_treatment: "Yes, but I'm not currently in treatment.",
      comfortable_discussing_mental_health: "Yes, I'm very open about it.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Islam",
      received_a_diagnosis: "Yes",
      age: 28,
      gender_identity: "Male",
      sexual_orientation: "Straight",
      religious_identity: "Yes, I am religious.",

    },
    interestsAndQuestions:
    {
      depression: false,
      anxiety: true,
      bipolar: false,
      ptsd: false,
      ocd: true,
      schizophrenia: true,
      eatingDisorders: false,
      other: false,
      eating_disorders: false,
      copingTechniques: false,
      personalStories: true,
      medication: true,
      reducingStigma: false,
      healthyLifestyle: true,
      spirituality: false,
      otherInterests: false,
      meditation: true,
      creativeActivities: false,
      talkToFriends: false,
      exercise: false,
      seekingHelp: true,
      otherCoping: false,
      creative_activities: false,
      talking_to_friends_family: false,
      exercising: true,
      professional_help: true,
      copingother: true,
      coping_techniques: true,
      personal_stories: true,
      reducing_stigma: true,
      healthy_lifestyle: false
    },

    pendingFriends: []
  },
  {
    firstName: "Ella",
    surName: "Garcia",
    email: "ella@example.com",
    age: 26,
    password: hashedPassword14,
    gender: "Female",
    verification: true,
    user_profile_pic: "user_default_female.png",
    userProfile: {
      primary_motivation: "To provide support and help to others",
      professional_treatment: "Yes, I am currently receiving treatment.",
      comfortable_discussing_mental_health: "Yes, I'm very open about it.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Atheism",
      received_a_diagnosis: "Yes",
      age: 26,
      gender_identity: "Female",
      sexual_orientation: "Lesbian",
      religious_identity: "No, I am not religious.",
   
    },
    interestsAndQuestions:
    {
      depression: true,
      anxiety: false,
      bipolar: false,
      ptsd: false,
      ocd: false,
      schizophrenia: true,
      eatingDisorders: true,
      other: true,
      eating_disorders: false,
      copingTechniques: true,
      personalStories: false,
      medication: false,
      reducingStigma: false,
      healthyLifestyle: false,
      spirituality: true,
      otherInterests: true,
      meditation: false,
      creativeActivities: true,
      talkToFriends: false,
      exercise: true,
      seekingHelp: true,
      otherCoping: false,
      creative_activities: true,
      talking_to_friends_family: false,
      exercising: false,
      professional_help: false,
      copingother: false,
      coping_techniques: true,
      personal_stories: false,
      reducing_stigma: false,
      healthy_lifestyle: true
    },
    pendingFriends: []
  },
  {
    firstName: "Aarav",
    surName: "Verma",
    email: "aarav@example.com",
    age: 30,
    password: hashedPassword15,
    gender: "Male",
    verification: true,
    user_profile_pic: "user_default_male.png",
    userProfile: {
      primary_motivation: "To gain knowledge about mental health and related topics",
      professional_treatment: "No, and I am not interested in seeking treatment.",
      comfortable_discussing_mental_health: "Somewhat, depending on the context.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Hinduism",
      received_a_diagnosis: "No",
      age: 30,
      gender_identity: "Male",
      sexual_orientation: "Straight",
      religious_identity: "Yes, I am religious.",

    },
    interestsAndQuestions:
    {
      depression: false,
      anxiety: true,
      bipolar: true,
      ptsd: true,
      ocd: false,
      schizophrenia: false,
      eatingDisorders: true,
      other: true,
      eating_disorders: true,
      copingTechniques: false,
      personalStories: false,
      medication: true,
      reducingStigma: true,
      healthyLifestyle: false,
      spirituality: false,
      otherInterests: true,
      meditation: false,
      creativeActivities: false,
      talkToFriends: true,
      exercise: true,
      seekingHelp: false,
      otherCoping: false,
      creative_activities: false,
      talking_to_friends_family: true,
      exercising: false,
      professional_help: true,
      copingother: false,
      coping_techniques: true,
      personal_stories: true,
      reducing_stigma: false,
      healthy_lifestyle: true
    },
    pendingFriends: []
  },
  {
    firstName: "Aisha",
    surName: "Rahman",
    email: "aisha@example.com",
    age: 28,
    password: hashedPassword16,
    gender: "Female",
    verification: true,
    user_profile_pic: "user_default_female.png",
    userProfile: {
      primary_motivation: "To gain knowledge about mental health and related topics",
      professional_treatment: "Yes, but I'm not currently in treatment.",
      comfortable_discussing_mental_health: "Yes, I'm very open about it.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Islam",
      received_a_diagnosis: "Yes",
      age: 28,
      gender_identity: "Female",
      sexual_orientation: "Straight",
      religious_identity: "Yes, I am religious.",
  
    },
    interestsAndQuestions:
    {
      depression: false,
      anxiety: false,
      bipolar: false,
      ptsd: true,
      ocd: false,
      schizophrenia: true,
      eatingDisorders: true,
      other: true,
      eating_disorders: true,
      copingTechniques: false,
      personalStories: true,
      medication: false,
      reducingStigma: false,
      healthyLifestyle: false,
      spirituality: true,
      otherInterests: true,
      meditation: false,
      creativeActivities: true,
      talkToFriends: true,
      exercise: true,
      seekingHelp: true,
      otherCoping: true,
      creative_activities: false,
      talking_to_friends_family: false,
      exercising: true,
      professional_help: true,
      copingother: true,
      coping_techniques: false,
      personal_stories: true,
      reducing_stigma: false,
      healthy_lifestyle: true
    },
    pendingFriends: []
  },
  {
    firstName: "Lucas",
    surName: "Anderson",
    email: "lucas@example.com",
    age: 32,
    password: hashedPassword17,
    gender: "Male",
    user_profile_pic: "user_default_male.png",
    verification: true,
    userProfile: {
      primary_motivation: "To seek understanding and support from others",
      professional_treatment: "No, and I am not interested in seeking treatment.",
      comfortable_discussing_mental_health: "No, I prefer to keep it private.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Atheism",
      received_a_diagnosis: "No",
      age: 32,
      gender_identity: "Male",
      sexual_orientation: "Bisexual",
      religious_identity: "No, I am not religious.",

    },
    interestsAndQuestions:
    {
      depression: true,
      anxiety: true,
      bipolar: true,
      ptsd: false,
      ocd: false,
      schizophrenia: false,
      eatingDisorders: false,
      other: false,
      eating_disorders: false,
      copingTechniques: true,
      personalStories: true,
      medication: false,
      reducingStigma: true,
      healthyLifestyle: false,
      spirituality: false,
      otherInterests: false,
      meditation: false,
      creativeActivities: true,
      talkToFriends: false,
      exercise: false,
      seekingHelp: true,
      otherCoping: false,
      creative_activities: true,
      talking_to_friends_family: true,
      exercising: false,
      professional_help: false,
      copingother: false,
      coping_techniques: false,
      personal_stories: false,
      reducing_stigma: true,
      healthy_lifestyle: true
    },
    pendingFriends: []
  },
  
    {
      firstName: "Alice",
      surName: "Johnson",
      email: "alice.johnson@example.com",
      age: 28,
      password:hashedPassword18,
      gender: "Female",
      verification: true,
      userProfile: {
        primary_motivation: "To seek understanding and support from others",
        professional_treatment: "Yes, I am currently receiving treatment.",
        comfortable_discussing_mental_health: "Yes, I'm very open about it.",
        connect_with_others: "Yes, that would be valuable to me.",
        religious: "Christianity",
        received_a_diagnosis: "Yes",
        age: 28,
        gender_identity: "Female",
        sexual_orientation: "Bisexual",
        religious_identity: "I am spiritual but not religious."
      },
      user_profile_pic: "user_default_female.png",
      interestsAndQuestions: {
        depression: true,
        anxiety: true,
        bipolar: false,
        ptsd: false,
        ocd: true,
        schizophrenia: false,
        eatingDisorders: false,
        other: false,
        eating_disorders: false,
        copingTechniques: true,
        personalStories: true,
        medication: false,
        reducingStigma: true,
        healthyLifestyle: true,
        spirituality: false,
        otherInterests: false,
        meditation: true,
        creativeActivities: true,
        talkToFriends: false,
        exercise: true,
        seekingHelp: true,
        otherCoping: false,
        creative_activities: false,
        talking_to_friends_family: true,
        exercising: true,
        professional_help: true,
        copingother: false,
        coping_techniques: false,
        personal_stories: true,
        reducing_stigma: false,
        healthy_lifestyle: true
      }
    },

  
      {
        firstName: "Sara",
        surName: "Chung",
        email: "sara.chung@example.com",
        age: 25,
        password: hashedPassword19,
        gender: "Female",
        verification: true,
        userProfile: {
          primary_motivation: "To seek understanding and support from others",
          professional_treatment: "Yes, I am currently receiving treatment.",
          comfortable_discussing_mental_health: "Yes, I'm very open about it.",
          connect_with_others: "Yes, that would be valuable to me.",
          religious: "Other",
          received_a_diagnosis: "Yes",
          age: 25,
          gender_identity: "Female",
          sexual_orientation: "Bisexual",
          religious_identity: "No, I am not religious."
        },
        user_profile_pic: "user_default_female.png",
        interestsAndQuestions: {
          depression: true,
          anxiety: true,
          bipolar: true,
          ptsd: false,
          ocd: false,
          schizophrenia: true,
          eatingDisorders: false,
          other: false,
          eating_disorders: false,
          copingTechniques: true,
          personalStories: true,
          medication: true,
          reducingStigma: true,
          healthyLifestyle: true,
          spirituality: false,
          otherInterests: false,
          meditation: true,
          creativeActivities: true,
          talkToFriends: true,
          exercise: false,
          seekingHelp: true,
          otherCoping: true,
          creative_activities: true,
          talking_to_friends_family: true,
          exercising: false,
          professional_help: true,
          copingother: false,
          coping_techniques: false,
          personal_stories: true,
          reducing_stigma: false,
          healthy_lifestyle: true
        }
      },
      {
        firstName: "Ahmed",
        surName: "Rahman",
        email: "ahmed.rahman@example.com",
        age: 30,
        password: hashedPassword20,
        gender: "Male",
        verification: true,
        userProfile: {
          primary_motivation: "To provide support and help to others",
          professional_treatment: "Yes, I am currently receiving treatment.",
          comfortable_discussing_mental_health: "Somewhat, depending on the context.",
          connect_with_others: "Yes, that would be valuable to me.",
          religious: "Islam",
          received_a_diagnosis: "No",
          age: 30,
          gender_identity: "Male",
          sexual_orientation: "Straight",
          religious_identity: "Yes, I am religious."
        },
        user_profile_pic: "user_default_male.png",
        interestsAndQuestions: {
          depression: true,
          anxiety: false,
          bipolar: true,
          ptsd: true,
          ocd: false,
          schizophrenia: false,
          eatingDisorders: false,
          other: false,
          eating_disorders: false,
          copingTechniques: true,
          personalStories: false,
          medication: true,
          reducingStigma: true,
          healthyLifestyle: true,
          spirituality: true,
          otherInterests: true,
          meditation: false,
          creativeActivities: true,
          talkToFriends: true,
          exercise: true,
          seekingHelp: true,
          otherCoping: false,
          creative_activities: true,
          talking_to_friends_family: true,
          exercising: true,
          professional_help: true,
          copingother: true,
          coping_techniques: false,
          personal_stories: false,
          reducing_stigma: false,
          healthy_lifestyle: true
        }
      },
   
        {
          firstName: "Ravi",
          surName: "Nguyen",
          email: "ravi.nguyen@example.com",
          age: 34,
          password: hashedPassword21,
          gender: "Male",
          verification: true,
          userProfile: {
            primary_motivation: "To provide support and help to others",
            professional_treatment: "Yes, I am currently receiving treatment.",
            comfortable_discussing_mental_health: "Yes, I'm very open about it.",
            connect_with_others: "Yes, that would be valuable to me.",
            religious: "Atheism",
            received_a_diagnosis: "Yes",
            age: 34,
            gender_identity: "Male",
            sexual_orientation: "Gay",
            religious_identity: "No, I am not religious."
          },
          user_profile_pic: "user_default_male.png",
          interestsAndQuestions: {
            depression: true,
            anxiety: true,
            bipolar: true,
            ptsd: false,
            ocd: true,
            schizophrenia: false,
            eatingDisorders: false,
            other: false,
            eating_disorders: false,
            copingTechniques: true,
            personalStories: true,
            medication: true,
            reducingStigma: true,
            healthyLifestyle: false,
            spirituality: true,
            otherInterests: true,
            meditation: true,
            creativeActivities: false,
            talkToFriends: true,
            exercise: true,
            seekingHelp: true,
            otherCoping: false,
            creative_activities: false,
            talking_to_friends_family: true,
            exercising: true,
            professional_help: true,
            copingother: true,
            coping_techniques: true,
            personal_stories: false,
            reducing_stigma: true,
            healthy_lifestyle: true
          }
        },
        {
          firstName: "Zara",
          surName: "Gonzalez",
          email: "zara.gonzalez@example.com",
          age: 29,
          password: hashedPassword22,
          gender: "Female",
          verification: true,
          userProfile: {
            primary_motivation: "To provide support and help to others",
            professional_treatment: "No, but I'm considering seeking treatment.",
            comfortable_discussing_mental_health: "Somewhat, depending on the context.",
            connect_with_others: "Yes, that would be valuable to me.",
            religious: "Other",
            received_a_diagnosis: "No",
            age: 29,
            gender_identity: "Female",
            sexual_orientation: "Queer",
            religious_identity: "No, I am not religious."
          },
          user_profile_pic: "user_default_female.png",
          interestsAndQuestions: {
            depression: true,
            anxiety: false,
            bipolar: false,
            ptsd: false,
            ocd: true,
            schizophrenia: false,
            eatingDisorders: false,
            other: false,
            eating_disorders: false,
            copingTechniques: true,
            personalStories: true,
            medication: true,
            reducingStigma: true,
            healthyLifestyle: true,
            spirituality: false,
            otherInterests: true,
            meditation: true,
            creativeActivities: true,
            talkToFriends: true,
            exercise: false,
            seekingHelp: true,
            otherCoping: true,
            creative_activities: true,
            talking_to_friends_family: true,
            exercising: false,
            professional_help: true,
            copingother: true,
            coping_techniques: true,
            personal_stories: true,
            reducing_stigma: true,
            healthy_lifestyle: false
          }
        },
    
          {
            firstName: "Aliyah",
            surName: "Kumar",
            email: "aliyah.kumar@example.com",
            age: 22,
            password: hashedPassword23,
            gender: "Female",
            verification: true,
            userProfile: {
              primary_motivation: "To gain knowledge about mental health and related topics",
              professional_treatment: "No, and I am not interested in seeking treatment.",
              comfortable_discussing_mental_health: "Yes, I'm very open about it.",
              connect_with_others: "I'm open to it, but it's not a priority.",
              religious: "Hinduism",
              received_a_diagnosis: "No",
              age: 22,
              gender_identity: "Female",
              sexual_orientation: "Other",
              religious_identity: "Yes, I am religious."
            },
            user_profile_pic: "user_default_female.png",
            interestsAndQuestions: {
              depression: false,
              anxiety: true,
              bipolar: false,
              ptsd: true,
              ocd: false,
              schizophrenia: true,
              eatingDisorders: false,
              other: true,
              eating_disorders: true,
              copingTechniques: false,
              personalStories: true,
              medication: true,
              reducingStigma: false,
              healthyLifestyle: true,
              spirituality: true,
              otherInterests: true,
              meditation: false,
              creativeActivities: true,
              talkToFriends: true,
              exercise: false,
              seekingHelp: true,
              otherCoping: true,
              creative_activities: true,
              talking_to_friends_family: true,
              exercising: true,
              professional_help: false,
              copingother: false,
              coping_techniques: true,
              personal_stories: true,
              reducing_stigma: false,
              healthy_lifestyle: true
            }
          },
          {
            firstName: "Leila",
            surName: "Martinez",
            email: "leila.martinez@example.com",
            age: 27,
            password: hashedPassword24,
            gender: "Female",
            verification: true,
            userProfile: {
              primary_motivation: "To provide support and help to others",
              professional_treatment: "Yes, I am currently receiving treatment.",
              comfortable_discussing_mental_health: "Somewhat, depending on the context.",
              connect_with_others: "Yes, that would be valuable to me.",
              religious: "Christianity",
              received_a_diagnosis: "Yes",
              age: 27,
              gender_identity: "Female",
              sexual_orientation: "Bisexual",
              religious_identity: "Yes, I am religious."
            },
            user_profile_pic: "user_default_female.png",
            interestsAndQuestions: {
              depression: true,
              anxiety: true,
              bipolar: true,
              ptsd: true,
              ocd: true,
              schizophrenia: false,
              eatingDisorders: true,
              other: true,
              eating_disorders: false,
              copingTechniques: true,
              personalStories: true,
              medication: true,
              reducingStigma: true,
              healthyLifestyle: true,
              spirituality: true,
              otherInterests: true,
              meditation: true,
              creativeActivities: true,
              talkToFriends: true,
              exercise: true,
              seekingHelp: true,
              otherCoping: true,
              creative_activities: true,
              talking_to_friends_family: true,
              exercising: true,
              professional_help: true,
              copingother: true,
              coping_techniques: true,
              personal_stories: true,
              reducing_stigma: true,
              healthy_lifestyle: true
            }
          },
      
        
        
    
    
  
];


