export const sampleUsers = [
  {
    firstName: "Liam",
    surName: "Smith",
    email: "liam@example.com",
    age: 28,
    password: "$2a$10$7GqEjL8bh7I09iAg9wGkVeX0L4b66prO4uHPscOzV4tcnHxJHo2o6",
    gender: "Male",
    verification: true,
    user_profile_pic: "user_default_male.png",
    userProfile: {
      primary_motivation: "To seek understanding and support from others",
      professional_treatment: "Yes, but I'm not currently in treatment.",
      comfortable_discussing_mental_health: "Yes, I'm very open about it.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Agnostic",
      received_a_diagnosis: "No",
      age: 28,
      gender_identity: "Male",
      sexual_orientation: "Gay",
      religious_identity: "No, I am not religious.",

    },
    interestsAndQuestions:{
      depression: false,
      anxiety: true,
      bipolar: false,
      ptsd: true,
      ocd: false,
      schizophrenia: false,
      eatingDisorders: true,
      other: false,
      eating_disorders: true,
      copingTechniques: true,
      personalStories: false,
      medication: true,
      reducingStigma: false,
      healthyLifestyle: false,
      spirituality: false,
      otherInterests: false,
      meditation: true,
      creativeActivities: false,
      talkToFriends: false,
      exercise: false,
      seekingHelp: true,
      otherCoping: true,
      creative_activities: true,
      talking_to_friends_family: true,
      exercising: true,
      professional_help: false,
      copingother: false,
      coping_techniques: false,
      personal_stories: false,
      reducing_stigma: false,
      healthy_lifestyle: false
    },
    pendingFriends: []
  },
  {
    firstName: "Sophia",
    surName: "Johnson",
    email: "sophia@example.com",
    age: 25,
    password: "$2a$10$na8mjBDyxK63cT5nB0L9HeX5NkzLNGCR1YzSD9QJENc5O5KQe5r9O",
    gender: "Female",
    verification: true,
    user_profile_pic: "user_default_female.png",
    userProfile: {
      primary_motivation: "To provide support and help to others",
      professional_treatment: "Yes, but I'm not currently in treatment.",
      comfortable_discussing_mental_health: "Yes, I'm very open about it.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Atheism",
      received_a_diagnosis: "No",
      age: 25,
      gender_identity: "Female",
      sexual_orientation: "Bisexual",
      religious_identity: "No, I am not religious.",

    },
    interestsAndQuestions:  {
      depression: true,
      anxiety: false,
      bipolar: false,
      ptsd: true,
      ocd: false,
      schizophrenia: true,
      eatingDisorders: false,
      other: true,
      eating_disorders: true,
      copingTechniques: true,
      personalStories: false,
      medication: true,
      reducingStigma: false,
      healthyLifestyle: false,
      spirituality: true,
      otherInterests: true,
      meditation: true,
      creativeActivities: false,
      talkToFriends: true,
      exercise: false,
      seekingHelp: false,
      otherCoping: true,
      creative_activities: true,
      talking_to_friends_family: true,
      exercising: true,
      professional_help: true,
      copingother: true,
      coping_techniques: true,
      personal_stories: true,
      reducing_stigma: false,
      healthy_lifestyle: true
    },
    pendingFriends: []
  },
  {
    firstName: "Muhammad",
    surName: "Ahmed",
    email: "muhammad@example.com",
    age: 32,
    password: "$2a$10$je8bCS7H2t0c3ahWnn4BEOzQD3ZxxURnW6xNJnjh.p/VbZ7U6YB0",
    user_profile_pic: "user_default_male.png",
    gender: "Male",
    verification: true,
    userProfile: {
      primary_motivation: "To gain knowledge about mental health and related topics",
      professional_treatment: "No, but I'm considering seeking treatment.",
      comfortable_discussing_mental_health: "Yes, I'm very open about it.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Islam",
      received_a_diagnosis: "No",
      age: 32,
      gender_identity: "Male",
      sexual_orientation: "Straight",
      religious_identity: "Yes, I am religious.",

    },
    interestsAndQuestions:  {
      depression: true,
      anxiety: false,
      bipolar: false,
      ptsd: true,
      ocd: false,
      schizophrenia: false,
      eatingDisorders: false,
      other: false,
      eating_disorders: false,
      copingTechniques: false,
      personalStories: false,
      medication: true,
      reducingStigma: true,
      healthyLifestyle: true,
      spirituality: true,
      otherInterests: false,
      meditation: false,
      creativeActivities: true,
      talkToFriends: true,
      exercise: true,
      seekingHelp: false,
      otherCoping: false,
      creative_activities: true,
      talking_to_friends_family: true,
      exercising: true,
      professional_help: false,
      copingother: true,
      coping_techniques: true,
      personal_stories: false,
      reducing_stigma: false,
      healthy_lifestyle: true
    },
    pendingFriends: []
  },
  {
    firstName: "Olivia",
    surName: "Martinez",
    email: "olivia@example.com",
    age: 29,
    password: "$2a$10$LHKn1eMZ3Zc0HgjOorakHugxz1U6s2xzEjls2HttfHwslgubqXGR.",
    user_profile_pic: "user_default_female.png",
    gender: "Female",
    verification: true,
    userProfile: {
      primary_motivation: "To provide support and help to others",
      professional_treatment: "No, and I am not interested in seeking treatment.",
      comfortable_discussing_mental_health: "No, I prefer to keep it private.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Buddhism",
      received_a_diagnosis: "No",
      age: 29,
      gender_identity: "Female",
      sexual_orientation: "Pansexual",
      religious_identity: "Yes, I am religious.",

    },
    interestsAndQuestions:
    {
      depression: true,
      anxiety: true,
      bipolar: false,
      ptsd: true,
      ocd: false,
      schizophrenia: true,
      eatingDisorders: false,
      other: true,
      eating_disorders: true,
      copingTechniques: true,
      personalStories: false,
      medication: false,
      reducingStigma: false,
      healthyLifestyle: true,
      spirituality: true,
      otherInterests: false,
      meditation: false,
      creativeActivities: false,
      talkToFriends: false,
      exercise: false,
      seekingHelp: false,
      otherCoping: true,
      creative_activities: true,
      talking_to_friends_family: true,
      exercising: true,
      professional_help: true,
      copingother: false,
      coping_techniques: true,
      personal_stories: true,
      reducing_stigma: true,
      healthy_lifestyle: true
    },

    pendingFriends: []
  },
  {
    firstName: "Mia",
    surName: "Brown",
    email: "mia@example.com",
    age: 27,
    password: "$2a$10$ML56TSGcdcvEmH4eb5LYT.aE0CM/ZdUalMawUIYFyXZQb0eGKp10O",
    user_profile_pic: "user_default_female.png",

    gender: "Female",
    verification: true,
    userProfile: {
      primary_motivation: "To seek understanding and support from others",
      professional_treatment: "Yes, I am currently receiving treatment.",
      comfortable_discussing_mental_health: "Yes, I'm very open about it.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Christianity",
      received_a_diagnosis: "Yes",
      age: 27,
      gender_identity: "Female",
      sexual_orientation: "Lesbian",
      religious_identity: "Yes, I am religious.",
    },
    interestsAndQuestions:  {
      depression: false,
      anxiety: true,
      bipolar: false,
      ptsd: false,
      ocd: true,
      schizophrenia: false,
      eatingDisorders: true,
      other: false,
      eating_disorders: true,
      copingTechniques: false,
      personalStories: false,
      medication: false,
      reducingStigma: true,
      healthyLifestyle: true,
      spirituality: true,
      otherInterests: false,
      meditation: false,
      creativeActivities: true,
      talkToFriends: true,
      exercise: true,
      seekingHelp: false,
      otherCoping: false,
      creative_activities: true,
      talking_to_friends_family: false,
      exercising: true,
      professional_help: true,
      copingother: false,
      coping_techniques: true,
      personal_stories: true,
      reducing_stigma: true,
      healthy_lifestyle: true
    },
    pendingFriends: []
  },
  {
    firstName: "Aryan",
    surName: "Patel",
    email: "aryan@example.com",
    age: 22,
    password: "$2a$10$/f2bQCH/rldgTTg3orw4quD/2NPlF4iHr9PVweLwW2ufb72E7Wj0u",
    gender: "Male",
    verification: true,
    user_profile_pic: "user_default_male.png",
    userProfile: {
      primary_motivation: "To seek understanding and support from others",
      professional_treatment: "No, and I am not interested in seeking treatment.",
      comfortable_discussing_mental_health: "Somewhat, depending on the context.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Hinduism",
      received_a_diagnosis: "No",
      age: 22,
      gender_identity: "Male",
      sexual_orientation: "Straight",
      religious_identity: "Yes, I am religious.",
 
    },
    interestsAndQuestions:  {
      depression: true,
      anxiety: false,
      bipolar: false,
      ptsd: false,
      ocd: true,
      schizophrenia: false,
      eatingDisorders: true,
      other: true,
      eating_disorders: true,
      copingTechniques: true,
      personalStories: false,
      medication: true,
      reducingStigma: true,
      healthyLifestyle: true,
      spirituality: true,
      otherInterests: false,
      meditation: true,
      creativeActivities: true,
      talkToFriends: false,
      exercise: false,
      seekingHelp: false,
      otherCoping: true,
      creative_activities: false,
      talking_to_friends_family: true,
      exercising: false,
      professional_help: false,
      copingother: false,
      coping_techniques: false,
      personal_stories: true,
      reducing_stigma: true,
      healthy_lifestyle: true
    },
    pendingFriends: []
  },
  {
    firstName: "Amina",
    surName: "Khan",
    email: "amina@example.com",
    age: 31,
    password: "$2a$10$0jLwEdapNBRcGHnr1..eJ.0ehzEf.jk3HKRfM7TVvyuTP4Z1ZjKK6",
    gender: "Female",
    verification: true,
    user_profile_pic: "user_default_female.png",
    userProfile: {
      primary_motivation: "To gain knowledge about mental health and related topics",
      professional_treatment: "Yes, but I'm not currently in treatment.",
      comfortable_discussing_mental_health: "Yes, I'm very open about it.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Islam",
      received_a_diagnosis: "Yes",
      age: 31,
      gender_identity: "Female",
      sexual_orientation: "Straight",
      religious_identity: "Yes, I am religious.",
      interestsAndQuestions:
      {
        depression: false,
        anxiety: true,
        bipolar: false,
        ptsd: true,
        ocd: false,
        schizophrenia: true,
        eatingDisorders: false,
        other: true,
        eating_disorders: false,
        copingTechniques: false,
        personalStories: true,
        medication: true,
        reducingStigma: true,
        healthyLifestyle: false,
        spirituality: true,
        otherInterests: false,
        meditation: true,
        creativeActivities: false,
        talkToFriends: true,
        exercise: false,
        seekingHelp: true,
        otherCoping: false,
        creative_activities: true,
        talking_to_friends_family: false,
        exercising: false,
        professional_help: false,
        copingother: false,
        coping_techniques: false,
        personal_stories: false,
        reducing_stigma: true,
        healthy_lifestyle: false
      },
    },
    pendingFriends: []
  },
  {
    firstName: "Zara",
    surName: "Ali",
    email: "zara@example.com",
    age: 33,
    password: "$2a$10$0KRbWV0twa2g/LbStHdOhu31yrXeEgZq1oQRpQxSOmc6aGKnlY5Ze",
    gender: "Female",
    verification: true,
    user_profile_pic: "user_default_female.png",
    userProfile: {
      primary_motivation: "To seek understanding and support from others",
      professional_treatment: "No, and I am not interested in seeking treatment.",
      comfortable_discussing_mental_health: "Somewhat, depending on the context.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Islam",
      received_a_diagnosis: "Yes",
      age: 33,
      gender_identity: "Female",
      sexual_orientation: "Straight",
      religious_identity: "Yes, I am religious.",

    },
    interestsAndQuestions:
    {
      depression: true,
      anxiety: true,
      bipolar: false,
      ptsd: true,
      ocd: false,
      schizophrenia: true,
      eatingDisorders: true,
      other: false,
      eating_disorders: false,
      copingTechniques: true,
      personalStories: true,
      medication: false,
      reducingStigma: false,
      healthyLifestyle: false,
      spirituality: false,
      otherInterests: true,
      meditation: true,
      creativeActivities: true,
      talkToFriends: false,
      exercise: false,
      seekingHelp: true,
      otherCoping: true,
      creative_activities: true,
      talking_to_friends_family: false,
      exercising: false,
      professional_help: false,
      copingother: false,
      coping_techniques: false,
      personal_stories: false,
      reducing_stigma: true,
      healthy_lifestyle: false
    },

    pendingFriends: []
  },
  {
    firstName: "David",
    surName: "Wilson",
    email: "david@example.com",
    age: 40,
    password: "$2a$10$hsvS5RF6h92Q0ZK6FfTQve9EYow29/N7o/e98NVa7aMmy7SZO/AvC", 
    gender: "Male",
    verification: true,
    user_profile_pic: "user_default_male.png",
    userProfile: {
      primary_motivation: "To seek understanding and support from others",
      professional_treatment: "Yes, I am currently receiving treatment.",
      comfortable_discussing_mental_health: "Yes, I'm very open about it.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Christianity",
      received_a_diagnosis: "Yes",
      age: 40,
      gender_identity: "Male",
      sexual_orientation: "Straight",
      religious_identity: "Yes, I am religious.",
    
    },
    interestsAndQuestions:
    {
      depression: true,
      anxiety: true,
      bipolar: true,
      ptsd: true,
      ocd: true,
      schizophrenia: false,
      eatingDisorders: false,
      other: true,
      eating_disorders: true,
      copingTechniques: false,
      personalStories: true,
      medication: true,
      reducingStigma: true,
      healthyLifestyle: false,
      spirituality: true,
      otherInterests: false,
      meditation: false,
      creativeActivities: false,
      talkToFriends: false,
      exercise: true,
      seekingHelp: false,
      otherCoping: true,
      creative_activities: false,
      talking_to_friends_family: false,
      exercising: true,
      professional_help: true,
      copingother: false,
      coping_techniques: false,
      personal_stories: false,
      reducing_stigma: true,
      healthy_lifestyle: false
    },
    pendingFriends: []
  },
  {
    firstName: "Amira",
    surName: "Hassan",
    email: "amira@example.com",
    age: 29,
    password: "$2a$10$C/G1qIb7ENqmsmLEgr86MuwCXZc0Hx12DR/hnKKMqvtayZXZLnmBW",
    gender: "Female",
    verification: true,
    user_profile_pic: "user_default_female.png",
    userProfile: {
      primary_motivation: "To provide support and help to others",
      professional_treatment: "No, and I am not interested in seeking treatment.",
      comfortable_discussing_mental_health: "Somewhat, depending on the context.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Islam",
      received_a_diagnosis: "No",
      age: 29,
      gender_identity: "Female",
      sexual_orientation: "Straight",
      religious_identity: "Yes, I am religious.",

    },
    interestsAndQuestions:
    {
      depression: false,
      anxiety: true,
      bipolar: true,
      ptsd: false,
      ocd: true,
      schizophrenia: true,
      eatingDisorders: true,
      other: false,
      eating_disorders: true,
      copingTechniques: false,
      personalStories: true,
      medication: true,
      reducingStigma: false,
      healthyLifestyle: false,
      spirituality: false,
      otherInterests: true,
      meditation: true,
      creativeActivities: false,
      talkToFriends: false,
      exercise: true,
      seekingHelp: true,
      otherCoping: false,
      creative_activities: false,
      talking_to_friends_family: true,
      exercising: true,
      professional_help: false,
      copingother: true,
      coping_techniques: true,
      personal_stories: false,
      reducing_stigma: false,
      healthy_lifestyle: false
    },
    pendingFriends: []
  },
  {
    firstName: "Leo",
    surName: "Miller",
    email: "leo@example.com",
    age: 35,
    password: "$2a$10$EwS6F13CMm4G4HY24F3dzOQbZVjzK7BePtPZL3eVr6SfD1sAadkAy",
    gender: "Male",
    verification: true,
    user_profile_pic: "user_default_male.png",
    userProfile: {
      primary_motivation: "To seek understanding and support from others",
      professional_treatment: "Yes, but I'm not currently in treatment.",
      comfortable_discussing_mental_health: "Yes, I'm very open about it.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Atheism",
      received_a_diagnosis: "No",
      age: 35,
      gender_identity: "Male",
      sexual_orientation: "Gay",
      religious_identity: "No, I am not religious.",

    },
    interestsAndQuestions:

    {
      depression: true,
      anxiety: true,
      bipolar: true,
      ptsd: false,
      ocd: false,
      schizophrenia: true,
      eatingDisorders: false,
      other: true,
      eating_disorders: false,
      copingTechniques: false,
      personalStories: false,
      medication: false,
      reducingStigma: false,
      healthyLifestyle: false,
      spirituality: false,
      otherInterests: false,
      meditation: false,
      creativeActivities: false,
      talkToFriends: true,
      exercise: true,
      seekingHelp: false,
      otherCoping: false,
      creative_activities: false,
      talking_to_friends_family: true,
      exercising: true,
      professional_help: false,
      copingother: false,
      coping_techniques: true,
      personal_stories: true,
      reducing_stigma: false,
      healthy_lifestyle: false
    },
    pendingFriends: []
  },
  {
    firstName: "Sofia",
    surName: "Lopez",
    email: "sofia@example.com",
    age: 23,
    password: "$2a$10$LtlZpxRPfAeX2q0eANg2ZOESyJ7QxsGtB37xK4yBQ3EJ9tUnR2Qfu",
    gender: "Female",
    verification: true,
    user_profile_pic: "user_default_female.png",
    userProfile: {
      primary_motivation: "To seek understanding and support from others",
      professional_treatment: "No, but I'm considering seeking treatment.",
      comfortable_discussing_mental_health: "Somewhat, depending on the context.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Christianity",
      received_a_diagnosis: "No",
      age: 23,
      gender_identity: "Female",
      sexual_orientation: "Bisexual",
      religious_identity: "Yes, I am religious.",

    },
    interestsAndQuestions:
    {
      depression: true,
      anxiety: false,
      bipolar: true,
      ptsd: true,
      ocd: true,
      schizophrenia: true,
      eatingDisorders: true,
      other: true,
      eating_disorders: true,
      copingTechniques: false,
      personalStories: true,
      medication: true,
      reducingStigma: false,
      healthyLifestyle: true,
      spirituality: false,
      otherInterests: true,
      meditation: true,
      creativeActivities: true,
      talkToFriends: true,
      exercise: false,
      seekingHelp: false,
      otherCoping: false,
      creative_activities: true,
      talking_to_friends_family: false,
      exercising: false,
      professional_help: false,
      copingother: true,
      coping_techniques: false,
      personal_stories: true,
      reducing_stigma: false,
      healthy_lifestyle: false
    },
    pendingFriends: []
  },
  {
    firstName: "Omar",
    surName: "Hussein",
    email: "omar@example.com",
    age: 28,
    password: "$2a$10$nB7nbD7i4OZgJzfq08inl.bOBlxtFoiOL2/wSUECFXZ//EpDOl7KW",
    gender: "Male",
    verification: true,
    user_profile_pic: "user_default_male.png",
    userProfile: {
      primary_motivation: "To gain knowledge about mental health and related topics",
      professional_treatment: "Yes, but I'm not currently in treatment.",
      comfortable_discussing_mental_health: "Yes, I'm very open about it.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Islam",
      received_a_diagnosis: "Yes",
      age: 28,
      gender_identity: "Male",
      sexual_orientation: "Straight",
      religious_identity: "Yes, I am religious.",

    },
    interestsAndQuestions:
    {
      depression: false,
      anxiety: true,
      bipolar: false,
      ptsd: false,
      ocd: true,
      schizophrenia: true,
      eatingDisorders: false,
      other: false,
      eating_disorders: false,
      copingTechniques: false,
      personalStories: true,
      medication: true,
      reducingStigma: false,
      healthyLifestyle: true,
      spirituality: false,
      otherInterests: false,
      meditation: true,
      creativeActivities: false,
      talkToFriends: false,
      exercise: false,
      seekingHelp: true,
      otherCoping: false,
      creative_activities: false,
      talking_to_friends_family: false,
      exercising: true,
      professional_help: true,
      copingother: true,
      coping_techniques: true,
      personal_stories: true,
      reducing_stigma: true,
      healthy_lifestyle: false
    },

    pendingFriends: []
  },
  {
    firstName: "Ella",
    surName: "Garcia",
    email: "ella@example.com",
    age: 26,
    password: "$2a$10$pgg6Q/CDuJYvVDgPzI1mb.Jkj.gBpAIdT73lywzw.9DDwU4lZITv.",
    gender: "Female",
    verification: true,
    user_profile_pic: "user_default_female.png",
    userProfile: {
      primary_motivation: "To provide support and help to others",
      professional_treatment: "Yes, I am currently receiving treatment.",
      comfortable_discussing_mental_health: "Yes, I'm very open about it.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Atheism",
      received_a_diagnosis: "Yes",
      age: 26,
      gender_identity: "Female",
      sexual_orientation: "Lesbian",
      religious_identity: "No, I am not religious.",
   
    },
    interestsAndQuestions:
    {
      depression: true,
      anxiety: false,
      bipolar: false,
      ptsd: false,
      ocd: false,
      schizophrenia: true,
      eatingDisorders: true,
      other: true,
      eating_disorders: false,
      copingTechniques: true,
      personalStories: false,
      medication: false,
      reducingStigma: false,
      healthyLifestyle: false,
      spirituality: true,
      otherInterests: true,
      meditation: false,
      creativeActivities: true,
      talkToFriends: false,
      exercise: true,
      seekingHelp: true,
      otherCoping: false,
      creative_activities: true,
      talking_to_friends_family: false,
      exercising: false,
      professional_help: false,
      copingother: false,
      coping_techniques: true,
      personal_stories: false,
      reducing_stigma: false,
      healthy_lifestyle: true
    },
    pendingFriends: []
  },
  {
    firstName: "Aarav",
    surName: "Verma",
    email: "aarav@example.com",
    age: 30,
    password: "$2a$10$BZGdJ6x.LzY0KJK1n8or7eL6t2V9ezy0n5wDGbVoh11X/wZn17IQ6",
    gender: "Male",
    verification: true,
    user_profile_pic: "user_default_male.png",
    userProfile: {
      primary_motivation: "To gain knowledge about mental health and related topics",
      professional_treatment: "No, and I am not interested in seeking treatment.",
      comfortable_discussing_mental_health: "Somewhat, depending on the context.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Hinduism",
      received_a_diagnosis: "No",
      age: 30,
      gender_identity: "Male",
      sexual_orientation: "Straight",
      religious_identity: "Yes, I am religious.",

    },
    interestsAndQuestions:
    {
      depression: false,
      anxiety: true,
      bipolar: true,
      ptsd: true,
      ocd: false,
      schizophrenia: false,
      eatingDisorders: true,
      other: true,
      eating_disorders: true,
      copingTechniques: false,
      personalStories: false,
      medication: true,
      reducingStigma: true,
      healthyLifestyle: false,
      spirituality: false,
      otherInterests: true,
      meditation: false,
      creativeActivities: false,
      talkToFriends: true,
      exercise: true,
      seekingHelp: false,
      otherCoping: false,
      creative_activities: false,
      talking_to_friends_family: true,
      exercising: false,
      professional_help: true,
      copingother: false,
      coping_techniques: true,
      personal_stories: true,
      reducing_stigma: false,
      healthy_lifestyle: true
    },
    pendingFriends: []
  },
  {
    firstName: "Aisha",
    surName: "Rahman",
    email: "aisha@example.com",
    age: 28,
    password: "$2a$10$rrpppxDlz1DCWNSK6xzZ9uiL8nbojP18PtDTwAn59ZkAawvZM2s1G",
    gender: "Female",
    verification: true,
    user_profile_pic: "user_default_female.png",
    userProfile: {
      primary_motivation: "To gain knowledge about mental health and related topics",
      professional_treatment: "Yes, but I'm not currently in treatment.",
      comfortable_discussing_mental_health: "Yes, I'm very open about it.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Islam",
      received_a_diagnosis: "Yes",
      age: 28,
      gender_identity: "Female",
      sexual_orientation: "Straight",
      religious_identity: "Yes, I am religious.",
  
    },
    interestsAndQuestions:
    {
      depression: false,
      anxiety: false,
      bipolar: false,
      ptsd: true,
      ocd: false,
      schizophrenia: true,
      eatingDisorders: true,
      other: true,
      eating_disorders: true,
      copingTechniques: false,
      personalStories: true,
      medication: false,
      reducingStigma: false,
      healthyLifestyle: false,
      spirituality: true,
      otherInterests: true,
      meditation: false,
      creativeActivities: true,
      talkToFriends: true,
      exercise: true,
      seekingHelp: true,
      otherCoping: true,
      creative_activities: false,
      talking_to_friends_family: false,
      exercising: true,
      professional_help: true,
      copingother: true,
      coping_techniques: false,
      personal_stories: true,
      reducing_stigma: false,
      healthy_lifestyle: true
    },
    pendingFriends: []
  },
  {
    firstName: "Lucas",
    surName: "Anderson",
    email: "lucas@example.com",
    age: 32,
    password: "$2a$10$vSwaqE9H0v.NHSdJ5m3i/eAdFlGMBTun.zvwzR71VAPKu0W7fEJZ.",
    gender: "Male",
    user_profile_pic: "user_default_male.png",
    verification: true,
    userProfile: {
      primary_motivation: "To seek understanding and support from others",
      professional_treatment: "No, and I am not interested in seeking treatment.",
      comfortable_discussing_mental_health: "No, I prefer to keep it private.",
      connect_with_others: "Yes, that would be valuable to me.",
      religious: "Atheism",
      received_a_diagnosis: "No",
      age: 32,
      gender_identity: "Male",
      sexual_orientation: "Bisexual",
      religious_identity: "No, I am not religious.",

    },
    interestsAndQuestions:
    {
      depression: true,
      anxiety: true,
      bipolar: true,
      ptsd: false,
      ocd: false,
      schizophrenia: false,
      eatingDisorders: false,
      other: false,
      eating_disorders: false,
      copingTechniques: true,
      personalStories: true,
      medication: false,
      reducingStigma: true,
      healthyLifestyle: false,
      spirituality: false,
      otherInterests: false,
      meditation: false,
      creativeActivities: true,
      talkToFriends: false,
      exercise: false,
      seekingHelp: true,
      otherCoping: false,
      creative_activities: true,
      talking_to_friends_family: true,
      exercising: false,
      professional_help: false,
      copingother: false,
      coping_techniques: false,
      personal_stories: false,
      reducing_stigma: true,
      healthy_lifestyle: true
    },
    pendingFriends: []
  },
  
    {
      firstName: "Alice",
      surName: "Johnson",
      email: "alice.johnson@example.com",
      age: 28,
      password:"$2a$10$XcbNUw.K7Z52jwTfd0U6nOmT3Z3PSQd83jNSe3ERbLD0p/b9uUMFC",
      gender: "Female",
      verification: true,
      userProfile: {
        primary_motivation: "To seek understanding and support from others",
        professional_treatment: "Yes, I am currently receiving treatment.",
        comfortable_discussing_mental_health: "Yes, I'm very open about it.",
        connect_with_others: "Yes, that would be valuable to me.",
        religious: "Christianity",
        received_a_diagnosis: "Yes",
        age: 28,
        gender_identity: "Female",
        sexual_orientation: "Bisexual",
        religious_identity: "I am spiritual but not religious."
      },
      user_profile_pic: "user_default_female.png",
      interestsAndQuestions: {
        depression: true,
        anxiety: true,
        bipolar: false,
        ptsd: false,
        ocd: true,
        schizophrenia: false,
        eatingDisorders: false,
        other: false,
        eating_disorders: false,
        copingTechniques: true,
        personalStories: true,
        medication: false,
        reducingStigma: true,
        healthyLifestyle: true,
        spirituality: false,
        otherInterests: false,
        meditation: true,
        creativeActivities: true,
        talkToFriends: false,
        exercise: true,
        seekingHelp: true,
        otherCoping: false,
        creative_activities: false,
        talking_to_friends_family: true,
        exercising: true,
        professional_help: true,
        copingother: false,
        coping_techniques: false,
        personal_stories: true,
        reducing_stigma: false,
        healthy_lifestyle: true
      }
    },

  
      {
        firstName: "Sara",
        surName: "Chung",
        email: "sara.chung@example.com",
        age: 25,
        password: "$2a$10$Y/BchmIglXs/3RqHlmj1leP9upbm8CxGwSfvoDnYMTL6Q1gujMwry",
        gender: "Female",
        verification: true,
        userProfile: {
          primary_motivation: "To seek understanding and support from others",
          professional_treatment: "Yes, I am currently receiving treatment.",
          comfortable_discussing_mental_health: "Yes, I'm very open about it.",
          connect_with_others: "Yes, that would be valuable to me.",
          religious: "Other",
          received_a_diagnosis: "Yes",
          age: 25,
          gender_identity: "Female",
          sexual_orientation: "Bisexual",
          religious_identity: "No, I am not religious."
        },
        user_profile_pic: "user_default_female.png",
        interestsAndQuestions: {
          depression: true,
          anxiety: true,
          bipolar: true,
          ptsd: false,
          ocd: false,
          schizophrenia: true,
          eatingDisorders: false,
          other: false,
          eating_disorders: false,
          copingTechniques: true,
          personalStories: true,
          medication: true,
          reducingStigma: true,
          healthyLifestyle: true,
          spirituality: false,
          otherInterests: false,
          meditation: true,
          creativeActivities: true,
          talkToFriends: true,
          exercise: false,
          seekingHelp: true,
          otherCoping: true,
          creative_activities: true,
          talking_to_friends_family: true,
          exercising: false,
          professional_help: true,
          copingother: false,
          coping_techniques: false,
          personal_stories: true,
          reducing_stigma: false,
          healthy_lifestyle: true
        }
      },
      {
        firstName: "Ahmed",
        surName: "Rahman",
        email: "ahmed.rahman@example.com",
        age: 30,
        password: "$2a$10$/JfdEp6ufnMzYkEfAe5r4OHFP9qzv1C2tjI7UJIt0F7O.lAr6BcFi",
        gender: "Male",
        verification: true,
        userProfile: {
          primary_motivation: "To provide support and help to others",
          professional_treatment: "Yes, I am currently receiving treatment.",
          comfortable_discussing_mental_health: "Somewhat, depending on the context.",
          connect_with_others: "Yes, that would be valuable to me.",
          religious: "Islam",
          received_a_diagnosis: "No",
          age: 30,
          gender_identity: "Male",
          sexual_orientation: "Straight",
          religious_identity: "Yes, I am religious."
        },
        user_profile_pic: "user_default_male.png",
        interestsAndQuestions: {
          depression: true,
          anxiety: false,
          bipolar: true,
          ptsd: true,
          ocd: false,
          schizophrenia: false,
          eatingDisorders: false,
          other: false,
          eating_disorders: false,
          copingTechniques: true,
          personalStories: false,
          medication: true,
          reducingStigma: true,
          healthyLifestyle: true,
          spirituality: true,
          otherInterests: true,
          meditation: false,
          creativeActivities: true,
          talkToFriends: true,
          exercise: true,
          seekingHelp: true,
          otherCoping: false,
          creative_activities: true,
          talking_to_friends_family: true,
          exercising: true,
          professional_help: true,
          copingother: true,
          coping_techniques: false,
          personal_stories: false,
          reducing_stigma: false,
          healthy_lifestyle: true
        }
      },
   
        {
          firstName: "Ravi",
          surName: "Nguyen",
          email: "ravi.nguyen@example.com",
          age: 34,
          password: "$2a$10$R/2doC7uJUsWnjvFXmH8M.0IhYDb09tFTjrmG7i2F.9eO6r3NWa.u",
          gender: "Male",
          verification: true,
          userProfile: {
            primary_motivation: "To provide support and help to others",
            professional_treatment: "Yes, I am currently receiving treatment.",
            comfortable_discussing_mental_health: "Yes, I'm very open about it.",
            connect_with_others: "Yes, that would be valuable to me.",
            religious: "Atheism",
            received_a_diagnosis: "Yes",
            age: 34,
            gender_identity: "Male",
            sexual_orientation: "Gay",
            religious_identity: "No, I am not religious."
          },
          user_profile_pic: "user_default_male.png",
          interestsAndQuestions: {
            depression: true,
            anxiety: true,
            bipolar: true,
            ptsd: false,
            ocd: true,
            schizophrenia: false,
            eatingDisorders: false,
            other: false,
            eating_disorders: false,
            copingTechniques: true,
            personalStories: true,
            medication: true,
            reducingStigma: true,
            healthyLifestyle: false,
            spirituality: true,
            otherInterests: true,
            meditation: true,
            creativeActivities: false,
            talkToFriends: true,
            exercise: true,
            seekingHelp: true,
            otherCoping: false,
            creative_activities: false,
            talking_to_friends_family: true,
            exercising: true,
            professional_help: true,
            copingother: true,
            coping_techniques: true,
            personal_stories: false,
            reducing_stigma: true,
            healthy_lifestyle: true
          }
        },
        {
          firstName: "Zara",
          surName: "Gonzalez",
          email: "zara.gonzalez@example.com",
          age: 29,
          password: "$2a$10$Q1A3weeirgWY3LvWvR/uPe8jU7cZ9TXd77Xf0y6j6eOrGNHUsPT5q",
          gender: "Female",
          verification: true,
          userProfile: {
            primary_motivation: "To provide support and help to others",
            professional_treatment: "No, but I'm considering seeking treatment.",
            comfortable_discussing_mental_health: "Somewhat, depending on the context.",
            connect_with_others: "Yes, that would be valuable to me.",
            religious: "Other",
            received_a_diagnosis: "No",
            age: 29,
            gender_identity: "Female",
            sexual_orientation: "Queer",
            religious_identity: "No, I am not religious."
          },
          user_profile_pic: "user_default_female.png",
          interestsAndQuestions: {
            depression: true,
            anxiety: false,
            bipolar: false,
            ptsd: false,
            ocd: true,
            schizophrenia: false,
            eatingDisorders: false,
            other: false,
            eating_disorders: false,
            copingTechniques: true,
            personalStories: true,
            medication: true,
            reducingStigma: true,
            healthyLifestyle: true,
            spirituality: false,
            otherInterests: true,
            meditation: true,
            creativeActivities: true,
            talkToFriends: true,
            exercise: false,
            seekingHelp: true,
            otherCoping: true,
            creative_activities: true,
            talking_to_friends_family: true,
            exercising: false,
            professional_help: true,
            copingother: true,
            coping_techniques: true,
            personal_stories: true,
            reducing_stigma: true,
            healthy_lifestyle: false
          }
        },
    
          {
            firstName: "Aliyah",
            surName: "Kumar",
            email: "aliyah.kumar@example.com",
            age: 22,
            password: "$2a$10$LpT9UJxGZib7hEpx6EmkwOtcCoZOEX3b5VleVYc02AitjAMuWabLy",
            gender: "Female",
            verification: true,
            userProfile: {
              primary_motivation: "To gain knowledge about mental health and related topics",
              professional_treatment: "No, and I am not interested in seeking treatment.",
              comfortable_discussing_mental_health: "Yes, I'm very open about it.",
              connect_with_others: "I'm open to it, but it's not a priority.",
              religious: "Hinduism",
              received_a_diagnosis: "No",
              age: 22,
              gender_identity: "Female",
              sexual_orientation: "Other",
              religious_identity: "Yes, I am religious."
            },
            user_profile_pic: "user_default_female.png",
            interestsAndQuestions: {
              depression: false,
              anxiety: true,
              bipolar: false,
              ptsd: true,
              ocd: false,
              schizophrenia: true,
              eatingDisorders: false,
              other: true,
              eating_disorders: true,
              copingTechniques: false,
              personalStories: true,
              medication: true,
              reducingStigma: false,
              healthyLifestyle: true,
              spirituality: true,
              otherInterests: true,
              meditation: false,
              creativeActivities: true,
              talkToFriends: true,
              exercise: false,
              seekingHelp: true,
              otherCoping: true,
              creative_activities: true,
              talking_to_friends_family: true,
              exercising: true,
              professional_help: false,
              copingother: false,
              coping_techniques: true,
              personal_stories: true,
              reducing_stigma: false,
              healthy_lifestyle: true
            }
          },
          {
            firstName: "Leila",
            surName: "Martinez",
            email: "leila.martinez@example.com",
            age: 27,
            password: "$2a$10$rNpUCqZiWLIZC5DSMN0/PeD7bNnUNq.33d/zlN5tqoGLX/kAfJf6e",
            gender: "Female",
            verification: true,
            userProfile: {
              primary_motivation: "To provide support and help to others",
              professional_treatment: "Yes, I am currently receiving treatment.",
              comfortable_discussing_mental_health: "Somewhat, depending on the context.",
              connect_with_others: "Yes, that would be valuable to me.",
              religious: "Christianity",
              received_a_diagnosis: "Yes",
              age: 27,
              gender_identity: "Female",
              sexual_orientation: "Bisexual",
              religious_identity: "Yes, I am religious."
            },
            user_profile_pic: "user_default_female.png",
            interestsAndQuestions: {
              depression: true,
              anxiety: true,
              bipolar: true,
              ptsd: true,
              ocd: true,
              schizophrenia: false,
              eatingDisorders: true,
              other: true,
              eating_disorders: false,
              copingTechniques: true,
              personalStories: true,
              medication: true,
              reducingStigma: true,
              healthyLifestyle: true,
              spirituality: true,
              otherInterests: true,
              meditation: true,
              creativeActivities: true,
              talkToFriends: true,
              exercise: true,
              seekingHelp: true,
              otherCoping: true,
              creative_activities: true,
              talking_to_friends_family: true,
              exercising: true,
              professional_help: true,
              copingother: true,
              coping_techniques: true,
              personal_stories: true,
              reducing_stigma: true,
              healthy_lifestyle: true
            }
          },
      
        
        
    
    
  
];


